holdings:
  - code: 515070.SH
    name: 人工智能ETF
    buy_date: "20260109"
    buy_price: 2.02
    shares: 10000
  - code: 159206.SZ
    name: 卫星ETF
    buy_date: "20260123"
    buy_price: 1.99
    shares: 10000
  - code: 159206.SZ
    name: 科创50ETF
    buy_date: "20260123"
    buy_price: 1.99
    shares: 10000
